prepend deploy script with docker install script

diff --git a/.github/workflows/actions.yaml b/.github/workflows/actions.yaml
--- a/.github/workflows/actions.yaml
+++ b/.github/workflows/actions.yaml
@@ -51,5 +51,15 @@ jobs:
           username: ${{ secrets.EC2_USERNAME }}
           key: ${{ secrets.EC2_SSH_KEY }}
           script: |
+            if ! command -v docker &> /dev/null
+              then
+                echo "Docker not found, installing..."
+                sudo apt-get update
+                sudo apt-get install -y docker.io
+                sudo systemctl enable docker
+                sudo systemctl start docker
+                sudo usermod -aG docker $USER
+            fi
+            
             docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-mlapp-three:latest
             docker run -d -p 80:8005 --name my-mlapp-three ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-mlapp-three:latest
